Agoric/agoric-3-proposals

.github/workflows/ci.yml, buildTestImages.ts, makeDockerfile.ts, runTestImages.ts, upgrade-test-scripts/start_agd.sh, upgrade-test-scripts/start_to_to.sh
=> feat: push completed image

.github/workflows/ci.yml, README.md
Publish multiplatform images for main branch pushes.
=> ci(docker): build multiplatform images on push to main or workflow dispatch

common.ts, proposals/16:upgrade-8/config.json, proposals/16:upgrade-8/package.json, proposals/29:upgrade-9/config.json, proposals/29:upgrade-9/package.json, proposals/34:upgrade-10/config.json, proposals/34:upgrade-10/package.json, proposals/43:upgrade-11/config.json, proposals/43:upgrade-11/package.json, proposals/49:smart-wallet-nft/config.json, proposals/49:smart-wallet-nft/package.json, proposals/53:kread-start/config.json, proposals/53:kread-start/package.json, proposals/55:statom-vaults/config.json, proposals/55:statom-vaults/package.json, proposals/63:upgrade-12/config.json, proposals/63:upgrade-12/package.json, proposals/b:zoe1/config.json, proposals/b:zoe1/package.json
I had a thought that each proposal test is a package, so let's put the essential info in the package.json.
Taking this further, the `test.sh` and `eval.sh` could be package scripts.
This just moves the config for now.
Tested by rebuilding Dockerfile and seeing that it's exactly the same.
=> refactor: config proposal within package.json

.github/workflows/ci.yml, README.md
Reverts Agoric/agoric-3-proposals#22
It's failing. We'll need another approach such as,
- https://github.com/Agoric/agoric-3-proposals/pull/32
=> Revert "ci(docker): build multiplatform images on push to main or workflow dispatch"

.github/workflows/ci.yml
A simple change to prepare for multiplatform docker builds (#32).
The plan:
1. ensure that `test-proposals (linux/amd64)` passes for this PR
2. get an approving review
3. change branch protection requirements from `test-proposals` to `test-proposals (linux/amd64)` and rapidly thereafter:
4. merge this PR to main
=> ci: add new `platform` matrix to be required

README.md, proposals/29:upgrade-9/test.sh, proposals/29:upgrade-9/use.sh
Closes: #40 
Has a couple more cleanups too
- docs: proposal type is in package.json, not config.json (redundant with https://github.com/Agoric/agoric-3-proposals/pull/42/) 
- feat: set minimum-gas-prices explicitly to zero
- test: consolidate upgrade-9 tests
=> stop minimum-gas warning

packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/proposals.ts
In the shuffle to Agoric-SDK and back, https://github.com/Agoric/agoric-3-proposals/pull/46 lost the `lastPassedProposal` functionality.
That made the `main` image include more pending proposals, which broke agoric-sdk integration builds. https://github.com/Agoric/agoric-sdk/pull/8731/commits/34fe9a4692ce687e70b294cfebfcf66f8630954f is a work-around that I'll revert after this image builds.
This fixed doesn't need a release because this new code won't execute outside this repo.
=> fix default entrypoint

.github/workflows/ci.yml
This is an optimisation to reduce the amount of disk space and build time needed on each worker.  It currently uses a `self-hosted` runner for creating ARM images, falling back to standard `ubuntu-latest` GitHub runners.
=> ci(docker): build each platform in a different worker

packages/synthetic-chain/package.json, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/proposals.ts, yarn.lock
Fixes needed for https://github.com/Agoric/agoric-sdk/pull/8635
- fix: append starting with an upgrade
- fix(deps): better-sqlite3
- chore: yarn version prerelease
Misc drive-by cleanup
- docs: 'subdir' is the default CoreEval source
- chore: remove dead THIS_NAME
- chore: remove superfluous jsdoc
I already published 0.0.2-0 prerelease so https://github.com/Agoric/agoric-sdk/pull/8635 can source it in CI. If there are changes requested I'll include them in this PR before merging and publishing 0.0.2.
=> fix 'append'

package.json, packages/synthetic-chain/cli.ts, packages/synthetic-chain/package.json, packages/synthetic-chain/src/cli/build.ts, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/tsconfig.json, packages/synthetic-chain/upgrade-test-scripts/start_ag0.sh
Follow-up to #52, but instead of relying on new commands and positional parameters, the base build info is read from the `package.json` enclosing the `proposals`. This allows using a single and simple `synthetic-chain build` command, whether in a3p itself or in other repos integrations. It also provides a place in the future to configure the build of other a3p like images.
I have manually locally tested this change with https://github.com/Agoric/agoric-sdk/pull/8743.
A new version of the `synthetic-chain` package still needs to be published if approved.
=> Read build info from package.json

packages/synthetic-chain/package.json, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/proposals.ts
Plumbing of `UPGRADE_INFO` seem to have disappeared with `synthetic-chain`. This adds the capability back.
Manually tested in `agoric-sdk` with a core proposal installing the network vat on top of https://github.com/Agoric/agoric-sdk/pull/8747
Released as 0.0.3
=> feat(synthetic-chain): add proposal upgradeInfo support

packages/synthetic-chain/src/lib/agd-lib.js, packages/synthetic-chain/src/lib/cliHelper.js, packages/synthetic-chain/upgrade-test-scripts/env_setup.sh, packages/synthetic-chain/upgrade-test-scripts/start_ag0.sh, packages/synthetic-chain/upgrade-test-scripts/start_to_to.sh, proposals/16:upgrade-8/use.sh
While trying to build Docker images with QEMU, I fixed a few issues with sensitivity to races and timeouts.  Here they are:
- abort on `PROPOSAL_STATUS_FAILED`, which means the upgrade was scheduled to start before the voting period was over
- if upgrade height is passed, still treat it as needing to kill the chain
- increase `software-upgrade` height to mitigate the `PROPOSAL_STATUS_FAILED` problems
- wait for block inclusion when submitting transactions
Also for my sanity when working on the `start_*.sh` scripts:
- alias `agd` to `ag0` in `start_ag0.sh` to reduce noise when trying to compare or copy-and-paste code from `start_to_to.sh`.
=> fix: miscellaneous cleanups

.github/workflows/ci.yml, .gitignore, README.md, docker-bake.hcl, packages/synthetic-chain/README.md, packages/synthetic-chain/cli.ts, packages/synthetic-chain/src/cli/build.ts, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/proposals.ts, proposals/16:upgrade-8/use.sh, proposals/34:upgrade-10/performActions.js, proposals/43:upgrade-11/performActions.js, proposals/b:zoe1/use.sh
closes: #25
Publishes "use" images so that consumers can rely on a certain state of state of the chain. They're published as tags matching the target, like `use-upgrade-9`. I experimented with having separate images names such as [a3p-use-upgrade8](https://github.com/agoric/agoric-3-proposals/pkgs/container/a3p-upgrade-8) but we agreed it's better to just use tags. They're all visible at https://ghcr.io/agoric/agoric-3-proposals. 
This isn't meant to push tags for "use" images out of PR builds. It does for review but once the PR is approved I'll change it to only push from the default branch. That sidesteps the issue of distinguishing use images by branch origin.
This PR has some other cleanup and refactoring along the way. I recommend reviewing by commit.
=> publish 'use' images

.github/workflows/ci.yml, README.md, package.json, packages/synthetic-chain/cli.ts, packages/synthetic-chain/package.json, packages/synthetic-chain/src/cli/build.ts, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/doctor.ts, packages/synthetic-chain/src/cli/run.ts, packages/synthetic-chain/upgrade-test-scripts/install_deps.sh
closes: #78 
CI time 62m vs [66m before the "use" PR](https://github.com/Agoric/agoric-3-proposals/actions/runs/7560953695/job/20588102989). (no statsig diff)
=> solve disk usage

.github/workflows/ci.yml, packages/synthetic-chain/cli.ts, packages/synthetic-chain/src/cli/build.ts, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/proposals.ts, packages/synthetic-chain/src/lib/agd-lib.ts, packages/synthetic-chain/upgrade-test-scripts/env_setup.sh, packages/synthetic-chain/upgrade-test-scripts/run_eval.sh, packages/synthetic-chain/upgrade-test-scripts/run_test.sh, packages/synthetic-chain/upgrade-test-scripts/run_use.sh, packages/synthetic-chain/upgrade-test-scripts/start_agd.sh, proposals/16:upgrade-8/use.sh, proposals/53:kread-start/eval.sh, proposals/64:crabble-start/test-crabble-start.js
Ancillary changes for https://github.com/Agoric/agoric-3-proposals/pull/88 that needn't wait for that PR itself to be landed.
=> misc improvements (caching, logging, robustness)

packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/upgrade-test-scripts/start_to_to.sh
https://github.com/Agoric/agoric-3-proposals/pull/88 broke the tacit API of what files are in the Docker images available to downstream builds.
The downstream should be copying its own dependencies into the filesystem so that they aren't coupled to the @agoric/synthetic-chain used to produce the upstream images.
That's apparently not the case for [some branch in agoric-sdk](https://github.com/Agoric/agoric-3-proposals/pull/88#discussion_r1480765464) so this is a stop-gap until further investigation.
=> fix: start_to_to.sh for backwards compat

packages/synthetic-chain/src/lib/commonUpgradeHelpers.js, packages/synthetic-chain/upgrade-test-scripts/env_setup.sh
Partially handle the new response shape for gov proposal queries.
With cosmos 0.46, the proposal has an `id` field instead of `proposal_id` (it also has `messages` instead of `content`, but it looks like nothing is making use of that field as of now).
This also checks the proposal status before making the deposit or voting on it, and handles failed proposals in more places.
=> fix: handle new gov proposal query shape

packages/synthetic-chain/package.json, packages/synthetic-chain/src/lib/core-eval-support.ts, packages/synthetic-chain/src/lib/core-eval.ts
`passCoreEvalProposal` was relying on a fake WebCache configured with a hard coded `submission` base dir, even though the actual bundles may be in a different location.
This PR removes the use of the WebCache by `passCoreEvalProposal` and extends the `BundleInfo` definition to include base dir details.
Tested as patch in https://github.com/Agoric/agoric-sdk/pull/8901
=> fix(synthetic-chain)!: bundle info with dir

packages/synthetic-chain/package.json, packages/synthetic-chain/src/lib/core-eval.ts
This removes the assertion that none of the bundles were previously installed.
Any already installed bundle will be skipped at the actual installation step.
=> allow CoreEval with same bundles

packages/synthetic-chain/src/lib/commonUpgradeHelpers.js, packages/synthetic-chain/src/lib/core-eval.ts, proposals/49:smart-wallet-nft/upgrade-wf.test.js
If multiple tests attempt to pass a core eval (or really any proposal) concurrently, `voteLatestProposalAndWait` would only find the latest proposal. This PR plumbs a config with the `title` and `description` of the core eval proposal, and uses the title to find the corresponding pending proposal (there is no way to look up a proposal by original tx submission). `evalBundles` is modified to generate a title based on the submission dir name.
=> fix: vote on proposal by title

.github/workflows/ci.yml, README.md, proposals/61:lo-bundle-cost/test.sh
closes: #121 
Pushing the "latest" image shouldn't build anything. Confirmed by manually triggering the workflow to get the steps that are skipped in normal PRs. https://github.com/Agoric/agoric-3-proposals/actions/runs/8250580844/job/22565552157
```
Push "latest" image                10s
```
=> fix stale "latest" image

packages/synthetic-chain/public/upgrade-test-scripts/env_setup.sh, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/README.md, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/gov1.key, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/gov2.key, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/gov3.key, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/user1.key, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/validator.key, packages/synthetic-chain/public/upgrade-test-scripts/run_prepare_zero.sh, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/lib/commonUpgradeHelpers.js, proposals/34:upgrade-10/upgradeHelpers.js
This PR moves keys to disk so they can be echo'd out when doing `docker exec -it ... /bin/bash`
=> Keys on disk

packages/synthetic-chain/package.json, packages/synthetic-chain/public/upgrade-test-scripts/env_setup.sh, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/README.md, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/gov1.key, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/gov2.key, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/gov3.key, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/user1.key, packages/synthetic-chain/public/upgrade-test-scripts/keys_for_test_only/validator.key, packages/synthetic-chain/public/upgrade-test-scripts/run_prepare_zero.sh, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/lib/commonUpgradeHelpers.js
Closes: #139 
With the [workaround](https://github.com/Agoric/agoric-3-proposals/issues/136#issuecomment-2034174218) suggested by @gacogo, we no longer need to persist the mnemonics on disk. This PR removes the mnemonics on disk.
=> feat: move mnemonics out of disk

proposals/65:upgrade-13/package.json, proposals/65:upgrade-13/post.test.js, proposals/65:upgrade-13/yarn.lock, proposals/71:upgrade-14/package.json, proposals/71:upgrade-14/tsconfig.json, proposals/71:upgrade-14/yarn.lock
The last two proposals, `upgrade-13` and `upgrade-14`, weren't using the latest synthetic-chain dep. The latest proposals are often looked to as examples for other proposals. Being on latest also helps eliminate variables in debugging https://github.com/Agoric/agoric-sdk/pull/9204
This updates them and also turns on `noEmit` in u14's tsconfig to resolve a warning.
=> bump synthetic-chain dep in u13 and u14

packages/synthetic-chain/public/upgrade-test-scripts/env_setup.sh, packages/synthetic-chain/public/upgrade-test-scripts/run_prepare.sh, packages/synthetic-chain/public/upgrade-test-scripts/run_prepare_zero.sh, packages/synthetic-chain/public/upgrade-test-scripts/start_to_to.sh, proposals/16:upgrade-8/use.sh, proposals/61:lo-bundle-cost/eval.sh
https://github.com/Agoric/agoric-3-proposals/pull/120 was failing due to insufficient gas. E.g. the [build for prepare-upgrade-14-rc1](https://depot.dev/orgs/gtcxrhgg4x/projects/bqgtmlhmh8/builds/l84q1nzvwj/logs/sha256:8feb171d3f7f35d5ad55bd881d1ae42973dbdb2261a23d0d86e78256c71d2920) had:
```
raw_log: 'out of gas in location: WritePerByte; gasWanted: 200000, gasUsed: 206121:
out of gas'
```
It has a fix but this pulls it out since that PR shouldn't merge to main.
This also includes the removal of the pending Zoe proposal because it's tested now in agoric-sdk and https://github.com/Agoric/agoric-3-proposals/pull/113, which will soon be merged.
=> fix submit-proposal gas

.github/actions/notify-status/action.yml, packages/synthetic-chain/public/upgrade-test-scripts/env_setup.sh
refs: #93 
We haven't seen that flake since the hypothesized fix https://github.com/Agoric/agoric-3-proposals/issues/93#issuecomment-1930672860
The debugging output of `netstat` causes the logs to grow too large for Github's UI to search them. So let's not wait any longer to remove the output.
I don't think this will really solve #93 so this doesn't close it
=> chore: remove netstat debugging

README.md
https://hub.cosmos.network/main/hub-tutorials/live-upgrade-tutorial.html in particular is now a 404
=> docs: Update URLs

packages/synthetic-chain/package.json, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/proposals.ts, packages/synthetic-chain/src/lib/cliHelper.ts, packages/synthetic-chain/src/lib/commonUpgradeHelpers.ts, packages/synthetic-chain/src/lib/constants.js, packages/synthetic-chain/src/lib/vstorage.js, packages/synthetic-chain/tsconfig.json, yarn.lock
- **chore: convert to .ts**
- **chore(types): runtime checks**
- **feat: assert ENV constants defined**
- **chore: convert cliHelper to .ts**
- **chore(types): use cosmic-proto**
=> adopt cosmic-proto types

packages/synthetic-chain/public/upgrade-test-scripts/env_setup.sh
The new approach works even when `agd` is not a child process of the current shell.
cf. https://github.com/Agoric/agoric-sdk/pull/9563/files#r1649820976
=> fix: Update the killAgd "wait for pid" behavior

packages/synthetic-chain/package.json, packages/synthetic-chain/src/lib/commonUpgradeHelpers.ts, packages/synthetic-chain/src/lib/econHelpers.js, packages/synthetic-chain/src/lib/vat-status.js, packages/synthetic-chain/src/lib/vstorage.js, packages/synthetic-chain/tsconfig.json
`getInstanceBoardId` had the wrong return type declared. This fixes that and updates `tsconfig` to check all JS so it doesn't happen again.
I published this as 0.2.1. Any changes requested I'll roll into 0.2.2.
=> fix lint and getInstanceBoardId type

packages/synthetic-chain/package.json, packages/synthetic-chain/src/cli/run.ts, yarn.lock
closes: #151
Debug mode had a convenience to mount the local `proposals` path so local changes would be reflected there. But because that file path also has platform-dependent files like `better_sqlite3.node` it would sometimes fail.
This stops that behavior and updates some help text to suggest alternatives.
It also bumps execa to fix a problem encountered while debugging,
- https://github.com/Agoric/agoric-sdk/pull/10027/
=> stop mounting fs in debug mode

CONTRIBUTING.md
Add detail to CONTRIBUTING.md on the life cycle of proposals, from `a3p-integration`, through releases to `agoric-3-proposals.
=>  update CONTRIBUTING with details on release process

packages/synthetic-chain/package.json, packages/synthetic-chain/public/upgrade-test-scripts/env_setup.sh
Make CI logs more readable by:
* prefixing lines with "waitForBlock"/"voteLatestProposalAndWait"/etc.
* always including details (iteration count, observed block height, proposal id, etc.)
* omitting output that doesn't convey new information "done", "reading", etc.)
=> chore(synthetic-chain): Improve env_setup.sh function output

packages/synthetic-chain/package.json, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/proposals.ts, packages/synthetic-chain/test/test-cli.ts
=> fix(synthetic-chain): Read proposals in sorted order

packages/synthetic-chain/package.json, packages/synthetic-chain/src/lib/commonUpgradeHelpers.ts
Duplicates d1ba3207b5511f8620d016b9d4440c3869127bc1 in the JS version of `waitForBlock`
=> chore(synthetic-chain): Improve JS waitForBlock output

packages/synthetic-chain/package.json, packages/synthetic-chain/public/upgrade-test-scripts/env_setup.sh, packages/synthetic-chain/src/lib/core-eval.ts
```diff
[n:upgrade-next] Starting agd
ENV_SETUP starting
ENV_SETUP finished
startAgd()
Loading slog sender modules: @agoric/telemetry/src/slog-file.js @agoric/telemetry/src/flight-recorder.js
2024-11-20T18:04:43.558Z launch-chain: Launching SwingSet kernel
-1310
+startAgd() at height 1310
waitForBlock waiting for 2 new block(s)...
2024-11-20T18:05:02.654Z launch-chain: Launched SwingSet kernel
2024-11-20T18:05:02.657Z block-manager: block 1310 begin
2024-11-20T18:05:03.050Z block-manager: block 1310 commit
```
=> chore(synthetic-chain): Replace bare block height output in startAgd

README.md
While reviewing the documentation in the **Images** section, I found a typo in the container registry address. The original commands contained:
```text
docker build -t ghrc.io/agoric/agoric-3-proposals:dev .
docker run  ghrc.io/agoric/agoric-3-proposals:dev
```
**Issue:** The address `ghrc.io` is incorrect and does not point to a valid container registry. The correct domain is `ghcr.io`, which is GitHub's official container registry.
**Fix:** The corrected commands are as follows:
```sh
docker build -t ghcr.io/agoric/agoric-3-proposals:dev .
docker run  ghcr.io/agoric/agoric-3-proposals:dev
```
This fix ensures that the commands work properly by pointing to the correct container registry address, preventing errors when attempting to build or run the image.
=> Fixed Typo in Container Registry Address Update README.md

packages/synthetic-chain/public/upgrade-test-scripts/env_setup.sh, packages/synthetic-chain/public/upgrade-test-scripts/run_eval.sh, packages/synthetic-chain/public/upgrade-test-scripts/run_test.sh, packages/synthetic-chain/public/upgrade-test-scripts/run_use.sh, packages/synthetic-chain/src/cli/build.ts
closes #xxxx
- Enables a hook `prepare-test` which can be used to run commands before starting the tests
- Saves the last known block height in a local file before killing the `agd` process
- Adds missing `killAgd` in stages missing this function call
Enables [docker progress logs verbosity](https://docs.docker.com/reference/cli/docker/buildx/build/#progress) through environmental variable `DOCKER_PROGRESS_FORMAT`. The `plain` progress format is handy for debugging.
=> feat: Prepare test hook

README.md, packages/synthetic-chain/src/cli/dockerfileGen.ts
Closes: #115
This omits `test*` from non-test images. Presumably no other stages depend on "test*" files. CI passing here is evidence of that in the a3p images. If any are affected in downsteam repos we can correct them.
=> copy 'test' files only in TEST stage

packages/synthetic-chain/package.json, packages/synthetic-chain/src/lib/agd-lib.ts, packages/synthetic-chain/src/lib/commonUpgradeHelpers.ts, packages/synthetic-chain/src/lib/core-eval-support.ts, packages/synthetic-chain/src/lib/core-eval.ts, yarn.lock
This solves a test problem so doesn't need a release.
@usmanmani1122 reports that #214 changes caused the tests to hang and timeout because of this tsimp issue,
- https://github.com/avajs/ava/issues/3349
To solve that this PR replaces `tsimp` with `ts-blank-space`.
=> test: replace tsimp with ts-blank-space

packages/synthetic-chain/package.json, packages/synthetic-chain/src/cli/doctor.ts, yarn.lock
_incidental_
Some users were encountering errors with locally built deps being included in the Docker build, causing:
```
proposals/n:upgrade-next/node_modules/@agoric/synthetic-chain/node_modules/better-sqlite3/build/Release/better_sqlite3.node: Mach-O 64-bit bundle arm64
```
This changes the `yarn install` in `doctor` to skip builds scripts so that the native dep is not created locally.
It also bumps some deps for hygiene and bumps the version number for publishing. Once this is approved I'll publish.
=> skip build in local yarn install

packages/synthetic-chain/src/lib/vat-status.js
#218 tried to add the termination status of vats to their details, but missed the case when the table is not present. This checks first.
`getVatDetailsFromID`, `getIncarnation`, and `getDetailsMatchingVats` should all be robust now.
=> Check if the vat.terminated table is present before relying on it

packages/synthetic-chain/public/upgrade-test-scripts/run_eval.sh
**eval.sh** vs. core-eval scripts/permits/bundles in **submission/**.
=> chore(synthetic-chain): Better document proposal eval configuration

.changeset/giant-jeans-jump.md, packages/synthetic-chain/src/lib/agd-lib.ts, packages/synthetic-chain/src/lib/cliHelper.ts, packages/synthetic-chain/src/lib/core-eval-support.ts, packages/synthetic-chain/src/lib/core-eval.ts
* Emit CLI commands to standard error
* Include `codespace` with `code` when dumping an abbreviated result
* Dump non-abbreviated result when there is a failure
It's probably time to publish after this lands.
=> chore(synthetic-chain): Improve output for debugging `agd` invocations

.github/workflows/trigger-mainfork-snapshot.yaml
This PR fixes the case of failing [Create Mainfork Snapshot](https://github.com/Agoric/agoric-3-proposals/actions/runs/15273907233/job/42955598280) build as the `gsutil` command fails in case the files to be deleted are not found
This step was added because the service account used in [mainfork-snapshot.sh](https://github.com/Agoric/agoric-3-proposals/blob/main/scripts/mainfork-snapshot.sh) script only had object creation access so it couldn't ovewrite an existing file. The service account in question is now granted that permission so the deletion step in the Github Action is no longer needed
The permissions can be viewed using
```
gcloud storage buckets get-iam-policy "gs://agoric-snapshots-public"
```
=> fix(ci): Move snapshot bucket overwrite permission to vm

.github/workflows/ci.yml, .github/workflows/docker-proposals.yml, packages/synthetic-chain/src/cli/cli.ts, packages/synthetic-chain/src/cli/dockerfileGen.ts, packages/synthetic-chain/src/cli/proposals.ts
We currently build all the layered proposal states, then run all the tests on them, and if both of those pass, publish all the unpublished states.  Aggressive caching with depot makes this work, but it overwhelms Depot with all the proposal interdependencies and the huge parallel build
This PR circumvents this with a matrix job that specifies a list of proposal ranges and the build/test/publish of each range is parallelized (as before), but the ranges are performed in series
=> ci(test-package): split into ranges

README.md
This PR updates the outdated link to the Agoric proposals explorer in the `README.md`. The original link (`https://bigdipper.live/agoric/proposals`) was no longer functional and has been replaced with the working link: [`https://agoric.explorers.guru/proposals`](https://agoric.explorers.guru/proposals).
This change only affects documentation. It does not impact the image building process or the behavior of any other repos.
No changes made to the library or its consumers.
re-open #250
=> fix: update dead link to Proposals Articul

.changeset/thin-ears-share.md, .github/workflows/ci.yml, packages/synthetic-chain/src/cli/cli.ts, packages/synthetic-chain/src/cli/proposals.ts
Follow-up to #262 to handle `fromTag` which is meant to indicate an image to start from that isn't available in the local set of proposals.
Fix CI to better honor `bypass:from-scratch`
=> fix handling of build config fromTag

.changeset/silly-seas-read.md, packages/synthetic-chain/src/cli/dockerfileGen.ts
Refs #286
This reverts https://github.com/Agoric/agoric-3-proposals/commit/9285e9bbf288df003812c7c9e89bef87c812e016. Since then we've change the building process in https://github.com/Agoric/agoric-3-proposals/pull/283 to build all targets once, and then push the built targets after tests pass.
Because of that, we were actually pushing the wrong image for `latest`, attempting to use a previously published one instead of the use target from the build. That results in an error when adding a new latest proposal.
=> fix(synthetic-chain): latest builds from multi-stage target
